export const prompts = [
  "A whimsical treehouse in a bioluminescent forest",
  "A steampunk-inspired coffee shop floating in the clouds early morning",
  "A peaceful, secret, magical garden where the flowers are made of stained glass",
  "A surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "A macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A whimsical kitchen in Whimsical Wonderland style with pastel holiday decor, candy-themed decorations, and playful holiday lights. The countertop features candy cane ornaments and colorful napkins. Ultra-realistic, high-quality photography",
  "A well muscled, 27 year old woman with a bandana in her hair - in the year 2205 A.D. - living in squallar. Realistic photo",
  "A photorealistic, studio lighting, 3 female basketball players in basketball uniforms whose faces are covered in glitter and feathers standing in a shimmering basketball court",
  "A crazy organic design of a catwalk stage, colorful female models, colorful silk, transparent acrylic, in the middle of the pyramids of Egypt daylight",
  "An anime style image of a humanoid fruit bat. She is a beautiful villain and has a bat face with fangs. She is in a dynamic pose and is performing a wing attack",
  "In the photo, there are two women sitting close together, laughing and enjoying each other's company. The woman on the left is younger, dressed in white, wearing a simple necklace, with her hair loosely tied back. The woman on the right has her hair in a low bun, wears a beige dress, a pearl necklace, and earrings. They seem to be sharing a joyful moment, with the older woman embracing the younger, showing a sense of closeness and affection. The background is neutral, keeping the focus on their expressions and bond.",
  "A comic book cover of a superhero wearing headphones",
  "A plush toy robot sitting against a yellow wall",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A smiling, fuzzy black cat with green eyes and a paw raised up to say HI",
  "Teenagers jumping from one multiverse to another represented as littlw worlds of specific interests and hobbies. Little Princess style, fantastic wonder",
  "A beautiful celestial space woman, praying with her power exploding from her mind's eye in the middle of her forehead. Alient, futuristic, sci-fi, photo realistic",
  "A powerful, dark Druid with the power to transform into animals",
  "A space shuttle out of earth into a brilliant starry sky, the shuttle's head coming towards the eye, space background, behind the earth, stratosphere visible, sun setting",
  "A winter wonderland scene of a clear, snowy sky with faint twinkling lights, snow on the ground with a twig tree on each side of the screen",
  "An emo Gothic teenager dressed with 2024 fashion on ancient Rome charriot during a tournament, Ben-Hur style, very wide angle, canon, 35 mm",
  "An anthropomorphic AI speech bubble, cute, talk, conversation, message, chat, character, bubbly, happy",
  "A dark, twisted fairy tale book for kids with old folklore illustrations of monsters and creatures",
  "Cover of VISION magazine, with yellow hair and blue eyes in the style of John Golson, oil painting, 3D render, surrealistic illustration, hyper realism, with the word VISION written on it, a man's head is split open showing colorful images of memories, by Kehinde Wiley, and James Jean, with abstract shapes, album cover art, and a holographic background with bold text that says Chaos is Madness",
  "Studio Ghibli-inspired style, a man stands up from a chair in a hospital room, his movements filled with urgency as he searches anxiously. He checks behind the bed, opens small cabinets, and looks under a table, all while casting worried glances over his shoulder towards his wife. His face is marked by concern and a hint of fear, drawn with soft yet expressive lines of typical Ghibli characters. The hospital room is warmly lit, with gentle, natural light streaming in through a window, illuminating the bed, shelves, and simple medical equipment.",
  "Illustration of a tense police investigation scene at night, featuring a diverse team of investigators gathered around a table covered with photographs and maps. The setting is dimly lit, emphasizing the pressure they feel. Include expressions of determination and concern on their faces, with a backdrop of a city skyline visible through a window. The atmosphere should convey urgency and the weight of the case, with scattered evidence and a chalkboard filled with clues in the background acuarela style",
  "A handsome young male doctor in green scrubs holds up an adorable golden retriever puppy with its tongue out, smiling and looking at the camera. The background is inside an animal hospital room with medical equipment visible.",
  "A woman is taking a selfie while getting a facial massage at the spa",
  "A minimalist film poster for Embers, a movie about memory and loss. The title is written in bold letters at the top of the frame. The poster features a close-up shot of an old photo paper showing part of a face with a tear under the wide-open eye. The background shows blurred images of elements from life, such as buildings, trees, flying objects, or faces. The poster has a black-and-white, grainy texture with a vintage look, inspired by the street photography of Robert Frank.",
  "Photorealistic portrait of a person wearing black vacuum-sealed armor, a face mask with red fangs and a metallic grid pattern, holding a katana in their hand, against a black background with dark lighting. The image has a hyper-realistic, cinematic photography style, with a full-body shot.",
  "A futuristic living room with a dog bowl, cartoon, cell-shaded",
  "A shiny burger in a church surrounded by a halo with a cathedral glass window as the background",
  "Shrek holding hands with Sailor Moon, flying and falling through space. Animation style.",
  "A gangster goat with a sloppy text tattoo and a rocket launcher on his back and an AK-47 in his hands. He wears jewelry, in comic style like the game Grand Theft Auto",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",

]