export function getRandomPrompt() {
  const randomIndex = Math.floor(Math.random() * prompts.length);
  return prompts[randomIndex];
}

export const prompts = [
  "A whimsical treehouse in a bioluminescent forest",
  "A steampunk-inspired coffee shop floating in the clouds, early morning sunrise, fresh and clean air, 50mm lens",
  "A peaceful, secret, magical garden where the flowers and flower petals are made of stained glass shards",
  "A surrealist dream-like oil painting of a cat playing checkers. The cat is confused; he doesn't know how to play, but he's trying to learn with his paws",
  "A macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art, photoshop",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs and a vibrant crowd, 50mm lens",
  "A whimsical kitchen in Whimsical Wonderland style with pastel holiday decor, candy-themed decorations, and playful holiday lights. The countertop features candy cane ornaments and colorful napkins. Ultra-realistic, high-quality photography",
  "A well muscled, 27 year old woman with a bandana in her hair - in the year 2205 A.D. - living in squallar. Realistic photo",
  "A photorealistic, studio lighting, 3 female basketball players in basketball uniforms whose faces are covered in glitter and feathers standing in a shimmering basketball court",
  "A crazy organic design of a catwalk stage, colorful female models, colorful silk, transparent acrylic, in the middle of the pyramids of Egypt daylight",
  "An anime, comic book style image of a humanoid fruit bat. She is a beautiful villain and has a bat face with fangs. She is in a dynamic pose and is performing a wing attack",
  "A comic book cover of a superhero wearing headphones, listening to R&B",
  "A plush toy robot sitting against a yellow wall, isolated, with a soft shadow",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A smiling, fuzzy black cat with green eyes and a paw raised up to say HI",
  "Teenagers jumping from one multiverse to another represented as little world ethereal bubbles of specific interests and hobbies. Little Princess style, fantasy and wonder. Be who you want to be.",
  "A beautiful celestial space woman, praying with her power exploding from her mind's eye in the middle of her forehead. Alien, futuristic, sci-fi, photo realistic, cosmic and spirtual",
  "A powerful, dark Druid with the power to transform into animals like a bear or panther",
  "A space shuttle out of earth into a brilliant starry sky, the shuttle's head coming towards the eye, space background, behind the earth, stratosphere visible, sun setting",
  "A winter wonderland scene of a clear, snowy sky with faint twinkling lights, snow on the ground with a twig tree on each side of the screen",
  "An emo Gothic teenager dressed with 2024 fashion on ancient Rome charriot during a tournament, Ben-Hur style, very wide angle, canon, 35 mm",
  "A dark, twisted fairy tale book for kids with old folklore illustrations of monsters and creatures",
  "Cover of VISION magazine, with yellow hair and blue eyes, oil painting, 3D render, surrealistic illustration, hyper realism, with the word VISION written on it, a man's head is split open showing colorful images of memories, with abstract shapes, album cover art, and a holographic background with bold text that says Chaos is Madness",
  "Studio Ghibli-inspired style, a man stands up from a chair in a hospital room, his movements filled with urgency as he searches anxiously. He checks behind the bed, opens small cabinets, and looks under a table, all while casting worried glances over his shoulder towards his wife. His face is marked by concern and a hint of fear, drawn with soft yet expressive lines of typical Ghibli characters. The hospital room is warmly lit, with gentle, natural light streaming in through a window, illuminating the bed, shelves, and simple medical equipment.",
  "Illustration of a tense police investigation scene at night, featuring a diverse team of investigators gathered around a table covered with photographs and maps. The setting is dimly lit, emphasizing the pressure they feel. Include expressions of determination and concern on their faces, with a backdrop of a city skyline visible through a window. The atmosphere should convey urgency and the weight of the case, with scattered evidence and a chalkboard filled with clues in the background acuarela style",
  "A handsome young male doctor in green scrubs holds up an adorable golden retriever puppy with its tongue out, smiling and looking at the camera. The background is inside an animal hospital room with medical equipment visible.",
  "A woman is taking a selfie while getting a facial massage at the spa",
  "A minimalist film poster for Embers, a movie about memory and loss. The title is written in bold letters at the top of the frame. The poster features a close-up shot of an old photo paper showing part of a face with a tear under the wide-open eye. The background shows blurred images of elements from life, such as buildings, trees, flying objects, or faces. The poster has a black-and-white, grainy texture with a vintage look, inspired by the street photography of Robert Frank.",
  "Photorealistic portrait of a person wearing black vacuum-sealed armor, a face mask with red fangs and a metallic grid pattern, holding a katana in their hand, against a black background with dark lighting. The image has a hyper-realistic, cinematic photography style, with a full-body shot.",
  "A futuristic empty living room with a dog bowl, cartoon, cell-shading, warm and cozy, and a window opened up to the outside planet",
  "A shiny burger in a church surrounded by a halo with a cathedral glass window as the background",
  "Shrek holding hands with Sailor Moon, flying and falling through space. Animation style.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "Three friends, both girls and boys, smiling brightly and enjoying a joyful moment together in a festive New Year's setting. They are surrounded by twinkling fairy lights, a beautifully decorated Christmas tree, and the warm glow of candles. The atmosphere is filled with laughter, happiness, and the magic of the holiday season. Snowflakes gently fall outside the window, adding to the cozy and celebratory vibe. Their expressions radiate genuine joy and connection, capturing the spirit of friendship and New Year's celebration",
  "A labyrinth made of floating glowing paths in an abstract space. At the center is a glowing compass or guiding star, symbolizing the role of meaning in navigating branding challenges. The pathways lead to vibrant elements like product designs, campaigns, and emotional connections, demonstrating purposeful creativity, soft pink and glossy palette, 3d forms",
  "Fête médiévale en rouge et noir. Old painting, chipped paint",
  "Super-realistic wide-angle shot of a massive, high-tech modern lobby hall with a glass top roof. In the center, a humanoid robot that looks 90% human, with blue robotic eyes and subtle steel plates showing on its arms, is meditating in a peaceful posture. Surrounding the humanoid robot are hundreds of people sitting in meditation, forming concentric circles. The hall is expansive, with sleek white walls, polished floors, and futuristic architecture. Natural light streams through the glass roof, casting soft shadows and creating a serene atmosphere. The camera captures the entire grandeur of the space, with a sharp focus on the humanoid robot in the center",
  "A picturesque Christmas panorama in Potsdam at night, featuring the city's historic architecture in the foreground. The sky is adorned with glowing origami stars in various shapes and colors. The ground is covered in sparkling snow, softly reflecting the scene. In the background, Santa Claus, dressed in his traditional red outfit, is seen crossing the night sky with his reindeer sleigh. The setting is illuminated by warm, festive lights, creating a cozy and magical Christmas atmosphere.",
  "Rooftop room, eating ramen, sunset night, lofi style, rooftop --v 6.0 --ar 3:2",
  "A surreal digital artwork of a quiet park at 2 AM, a glowing digital clock floating in the sky, a man pointing at it in astonishment, surrounded by surreal oversized flowers glowing under soft artificial light. A lone bench illuminated by a warm lamp, dreamy haze filling the scene. Whimsical and slightly eerie mood, vivid colors blending with soft gradients. Created Using: surrealist techniques, expressive character gestures, glowing neon highlights, intricate botanical details, ethereal lighting effects, dreamlike textures, whimsical composition, 8k quality, --ar 9:16",
]